---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options: {}
lint:
  name: yamllint
  enabled: False
platforms:
- name: default
  groups:
  - k8s
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        namespace: ${OC_PROJECT}
        operator_image: ${OPERATOR_IMAGE}
  lint:
    name: ansible-lint
    enabled: False
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
scenario:
  name: default
  test_sequence:
    - lint
    - syntax
    - converge