---
- name: Install software on client VMs
  hosts: ec2_hosts
  become: yes
  tasks:
    - name: Install docker
      package:
        name: docker
        state: present

    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: centos
        groups: docker
        append: yes

    - name: Start and enable docker
      service:
        name: docker
        enabled: true
        state: started

    - name: Download operator-sdk
      get_url:
        url: https://github.com/operator-framework/operator-sdk/releases/download/v0.9.0/operator-sdk-v0.9.0-x86_64-linux-gnu
        dest: /usr/local/bin/operator-sdk
        owner: centos
        group: centos
        mode: 0110

    - name: Download openshift client
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.1/linux/oc.tar.gz
        dest: /tmp/oc.tar.gz
        mode: 0500

    - name: Extract openshift client
      unarchive:
        src: /tmp/oc.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        owner: centos
        group: centos
        mode: 0110

    - name: Install git
      package:
        name: git
        state: present

    - name: Install epel-release
      package:
        name: epel-release
        state: present

    - name: Install pip
      package:
        name: python2-pip
        state: present

    - name: Install ansible
      pip:
        name: ansible
        state: present

    - name: Install gcc
      package:
        name: gcc
        state: present

    - name: Install python2-devel
      package:
        name: python2-devel
        state: present

    - name: Install molecule
      pip:
        name: molecule
        state: present
        extra_args: "--ignore-installed PyYAML"

    - name: Install kubernetes module
      pip:
        name: kubernetes
        state: present

    - name: Install openshift module
      pip:
        name: openshift
        state: present
      
    - name: Install jmespath module
      pip:
        name: jmespath
        state: present

    - name: Install ansible-runner
      pip:
        name: ansible-runner
        state: present

    - name: Clone ansible-runner-http repo
      git:
        repo: https://github.com/ansible/ansible-runner-http
        dest: /tmp/ansible-runner-http
        force: yes

    - name: Chmod setup.py script
      file:
        path: /tmp/ansible-runner-http/setup.py
        owner: root
        group: root
        mode: '0700'

    - name: Run 'setup.py build'
      command: python setup.py build
      args:
        chdir: /tmp/ansible-runner-http

    - name: Run 'setup.py install'
      command: python setup.py install
      args:
        chdir: /tmp/ansible-runner-http